# > 𝐥𝐚𝐨𝐬𝐡𝐮@𝐄𝐠𝐞𝐫𝐧 自用配置
# > 配置下载𝐔𝐑𝐋： https://raw.githubusercontent.com/jnlaoshu/MySelf/master/Egern/Profile.yaml
# > 𝐔𝐩𝐝𝐚𝐭𝐞: 2024.12.08 15:20

# > 开启ipv6支持
ipv6: true 

# > 允许外部连接通过 Wi-Fi 访问设备上的代理
allow_external_connections: true

# > 仅虚拟网接口模式
vif_only: true

# > 隐藏 VPN 图标
hide_vpn_icon: false

# > DNS 劫持
hijack_dns:
- '*:53'

# > 指定自定义的 GeoIP 数据库 URL
geoip_db_url: https://raw.githubusercontent.com/Masaiki/GeoIP2-CN/release/Country.mmdb
# > 指定自定义的 ASN 数据库 URL
asn_db_url: https://raw.githubusercontent.com/P3TERX/GeoLite.mmdb/download/GeoLite2-ASN.mmdb

# > 自定义的代理延迟测试 URL
proxy_latency_test_url: http://cp.cloudflare.com/generate_204
# > 自定义的直连延迟测试 URL
direct_latency_test_url: http://www.apple.com/library/test/success.html

# > 虚拟网络接口不使用默认的路由，由多个较小的路由切分用于解决某些问题。比如 HomeKit 的摄像头无法使用的问题
compat_route: false

# > 启用后系统会通过隧道路由网络流量，但为维持预期设备功能所必需的指定系统服务的流量除外
include_all_networks: false

# > 启用后系统将包含 Apple Push Notification 服务 (APN) 流量，但前提是包含所有网络也已启用
include_apns: false

# > 启用后系统会包含蜂窝网络服务，如 Wi-Fi 通话、彩信、短信和可视语音邮件，但前提是包含所有网络也已启用。该属性不会影响仅使用蜂窝网络的服务（如 VoLTE），系统会自动排除这些服务
include_cellular_services: false

# > 启用后系统将包含与本地网络上主机（如 AirPlay、AirDrop 和 CarPlay）的网络连接，但前提是包含所有网络也已启用。默认值是 false
include_local_networks: false

dns:
  bootstrap:
    - system  # 使用系统默认的DNS配置作为引导
  upstreams:  # 定义上游DNS服务器的列表
    Domestic: #使用国内公共DNS服务器作为上游服务器
    - https://dns.alidns.com/dns-query
    Foreign: #使用Google的公共DNS服务器作为上游服务器
    - https://dns.google/dns-query

# > 转发DNS请求的规则
  forward:  
  - wildcard:
      match: '*.cn'  # 将所有以.cn结尾的域名请求转发给国内公共DNS服务器
      value: Domestic
  - proxy_rule_set:  # 匹配 ACL4SSR 的中国域名列表中的域名
      match: https://github.com/ACL4SSR/ACL4SSR/raw/master/Clash/ChinaDomain.list
      value: Domestic  # 这些匹配的域名使用国内公共DNS服务器
  - proxy_rule_set:
      match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/ChinaMax/ChinaMax.list
      value: Domestic  # 这些匹配的域名使用国内公共DNS服务器
  - regex:
      match: ^ad\..*|^ads\..*  # 正则表达式匹配以"ad."或"ads."开头的域名（通常是广告相关的域名）
      value: quic://dns.adguard-dns.com  # 这些广告相关的域名使用AdGuard的QUIC DNS服务器
  - wildcard:
      match: '*'  # 匹配所有其他未被前述规则匹配的域名
      value: Foreign  # 将这些域名请求转发到系统默认的DNS服务器

# > 本地DNS解析的主机名映射
  hosts: 

    # > IPv6
    ip6-localhost: ::1 # IPv6 Localhost
    ip6-loopback: ::1 # IPv6 Loopback
    ip6-localnet: fe00::0 # IPv6 Link-Local
    ip6-mcastprefix: ff00::0 # IPv6 Multicast
    ip6-allnodes: ff02::1 # IPv6 All Nodes
    ip6-allrouters: ff02::2 # IPv6 All Routers
    ip6-allhosts: ff02::3 # IPv6 All Hosts

    # > Encrypted DNS
    dns.google: 8.8.8.8, 8.8.4.4, 2001:4860:4860::8888, 2001:4860:4860::8844 # https://dns.google/dns-query
    dns.alidns.com: 223.5.5.5, 223.6.6.6, 2400:3200:baba::1, 2400:3200::1 # https://dns.alidns.com/dns-query

    localhost: 127.0.0.1  # 将localhost解析为本地地址127.0.0.1   

# > 查询公共IP地址的URL，用于获取本机的公网IP地址  
  public_ip_lookup_url: https://ifconfig.me/ip  

# > 策略组配置列表
policy_groups:
- select:
    name: Apple
    policies:
    - DIRECT
    - 香港优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Apple.png
- select:
    name: AIGC
    policies:
    - 美国优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/ChatGPT.png    
- select:
    name: Google
    policies:
    - 香港优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Google_Search.png
- select:
    name: Microsoft
    policies:
    - DIRECT
    - 香港优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Microsoft.png
- select:
    name: PayPal
    policies:
    - 美国节点
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/PayPal.png
- select:
    name: Spotify
    policies:
    - 美国优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Spotify.png    
- select:
    name: Telegram
    policies:
    - 香港优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Telegram.png
- select:
    name: TikTok
    policies:
    - 日本优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/TikTok.png    
- select:
    name: Twitter
    policies:
    - 香港优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Twitter.png
- select:
    name: WeChat
    policies:
    - DIRECT
    - 香港优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/WeChat.png
- select:
    name: YouTube
    policies:
    - 香港优先
    flatten: true
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/YouTube.png
- auto_test:
    name: 香港节点
    policies:
    - 所有节点
    flatten: true
    filter: 🇭🇰|港|HK|Hong
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Hong_Kong.png
- auto_test:
    name: 美国节点
    policies:
    - 所有节点
    flatten: true
    filter: 🇺🇸|美|States|US
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/United_States.png
- auto_test:
    name: 台湾节点
    policies:
    - 所有节点
    flatten: true
    filter: 🇹🇼|台|TW|Tai
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Taiwan.png
- auto_test:
    name: 日本节点
    policies:
    - 所有节点
    flatten: true
    filter: 🇯🇵|日|日本|JP
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Japan.png
- auto_test:
    name: 狮城节点
    policies:
    - 所有节点
    flatten: true
    filter: 🇸🇬|新|新加坡|SG
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Singapore.png
- auto_test:
    name: 韩国节点
    policies:
    - 所有节点
    flatten: true
    filter: 🇰🇷|韩|KR|KOR|Korea
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/Korea.png    
- select:
    name: 其他节点
    policies:
    - 所有节点
    flatten: true
    filter: ^((?!🇭🇰|港|HK|Hong|🇹🇼|台|TW|Tai|🇯🇵|日|JP|Japan|🇸🇬|坡|狮城|SG|Singapore|🇰🇷|韩|KR|KOR|Korea|🇺🇸|美|US|States|American|Music).)*$
    icon: https://raw.githubusercontent.com/Koolson/Qure/master/IconSet/Color/World_Map.png
- external:
    name: 所有节点
    type: select
    urls:
    - https://sub.store/download/collection/AllServer?target=Egern
    icon: 🌹    
- select:
    name: 香港优先
    policies:
    - 香港节点
    - 美国节点
    - 狮城节点
    - 台湾节点
    - 日本节点
    - 韩国节点
    - 其他节点
    icon: 😊
- select:
    name: 美国优先
    policies:
    - 美国节点
    - 香港节点
    - 狮城节点
    - 台湾节点
    - 日本节点
    - 韩国节点
    - 其他节点
    icon: 🤣
- select:
    name: 日本优先
    policies:
    - 日本节点    
    - 美国节点
    - 台湾节点    
    - 韩国节点
    - 狮城节点
    - 香港节点
    - 其他节点
    icon: 🤣    

# > 代理规则列表
rules:
- domain_regex:
    match: ^ad\..*|^ads\..*
    policy: REJECT
- domain_suffix:
    match: dns.google.com
    policy: 香港优先
- domain_suffix:
    match: 8.8.8.8
    policy: 香港优先    
- rule_set:
    match: https://raw.githubusercontent.com/privacy-protection-tools/anti-AD/master/anti-ad-clash.yaml
    policy: REJECT
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple.list
    policy: Apple
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Apple/Apple_Domain.list
    policy: Apple
- rule_set:
    match: https://raw.githubusercontent.com/jnlaoshu/MySelf/refs/heads/main/Surge/Rules/AI.list
    policy: AIGC    
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Google/Google.list
    policy: Google
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Microsoft/Microsoft.list
    policy: Microsoft
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/PayPal/PayPal.list
    policy: PayPal    
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Spotify/Spotify.list
    policy: Spotify
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Telegram/Telegram.list
    policy: Telegram
- rule_set:
    match: https://raw.githubusercontent.com/jnlaoshu/MySelf/refs/heads/main/Egern/Rule/TikTok.yaml
    policy: TikTok    
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/Twitter/Twitter.list
    policy: Twitter
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/WeChat/WeChat.list
    policy: WeChat    
- rule_set:
    match: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Surge/YouTube/YouTube.list
    policy: YouTube

- domain:
    match: ifconfig.me
    policy: DIRECT
- domain_suffix:
    match: cn
    policy: DIRECT
- geoip:
    match: CN
    policy: DIRECT
- ip_cidr:
    match: 192.168.0.0/16
    policy: DIRECT
- ip_cidr:
    match: 10.0.0.0/8
    policy: DIRECT
- ip_cidr:
    match: 127.0.0.0/8
    policy: DIRECT
- ip_cidr:
    match: 172.16.0.0/12
    policy: DIRECT
- ip_cidr:
    match: 192.128.0.0/16
    policy: DIRECT
- ip_cidr:
    match: 224.0.0.0/24
    policy: DIRECT
- default:
    policy: 香港优先

# > MITM 配置
mitm:
  enabled: true
  ca_p12: egern.p12
  ca_passphrase: egern

# > 模块配置列表
modules:
- name: BoxJs
  url: https://raw.githubusercontent.com/chavyleung/scripts/master/box/rewrite/boxjs.rewrite.surge.sgmodule
  enabled: true
- name: ScriptHub
  url: https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/modules/script-hub.surge.sgmodule
  enabled: true
- name: Sub-Store
  url: https://raw.githubusercontent.com/sub-store-org/Sub-Store/master/config/Egern.yaml  
  enabled: true
- name: 'Spotify'
  url: https://raw.githubusercontent.com/app2smile/rules/master/module/spotify.module
  enabled: true
- name: 'WeatherKit'
  url: https://github.com/NSRingo/WeatherKit/releases/latest/download/WeatherKit.yaml
  enabled: true  
- name: ''
  url: https://raw.githubusercontent.com/Maasea/sgmodule/master/YouTube.Enhance.sgmodule
  enabled: true
- name: ''
  url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/Beta/12306%E5%8E%BB%E5%B9%BF%E5%91%8A.beta.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/Beta/%E5%8F%AF%E8%8E%89%E5%B9%BF%E5%91%8A%E8%BF%87%E6%BB%A4%E5%99%A8.beta.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/Beta/%E5%B0%8F%E7%BA%A2%E4%B9%A6%E5%8E%BB%E5%B9%BF%E5%91%8A.beta.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/Beta/%E5%BE%AE%E4%BF%A1%E5%85%AC%E4%BC%97%E5%8F%B7%E5%8E%BB%E5%B9%BF%E5%91%8A.beta.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E5%BE%AE%E4%BF%A1%E5%A4%96%E9%83%A8%E9%93%BE%E6%8E%A5%E8%A7%A3%E9%94%81.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E5%BE%AE%E4%BF%A1%E5%B0%8F%E7%A8%8B%E5%BA%8F%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E6%8B%BC%E5%A4%9A%E5%A4%9A%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E6%BB%B4%E6%BB%B4%E5%87%BA%E8%A1%8C%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E7%BE%8E%E5%9B%BE%E7%A7%80%E7%A7%80%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E7%BE%8E%E9%A2%9C%E7%9B%B8%E6%9C%BA%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E8%8F%9C%E9%B8%9F%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E9%85%B7%E6%88%91%E9%9F%B3%E4%B9%90%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E9%85%B7%E7%8B%97%E9%9F%B3%E4%B9%90%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E9%97%B2%E9%B1%BC%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E9%9B%AA%E7%90%83%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E9%AB%98%E5%BE%B7%E5%9C%B0%E5%9B%BE%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/QQ%E9%9F%B3%E4%B9%90%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/Spotify%E6%AD%8C%E8%AF%8D%E7%BF%BB%E8%AF%91.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E4%BA%91%E9%97%AA%E4%BB%98%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E4%BA%AC%E4%B8%9C%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E4%BC%98%E9%85%B7%E8%A7%86%E9%A2%91%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
- url: https://raw.githubusercontent.com/QingRex/LoonKissSurge/refs/heads/main/Surge/%E5%93%94%E5%93%A9%E5%93%94%E5%93%A9%E5%8E%BB%E5%B9%BF%E5%91%8A.sgmodule
  enabled: true
